apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SVestor/argocd-app.git
    targetRevision: HEAD 
    path: helm
  destination:
    server: https://kubernetes.default.svc 
    namespace: development

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  

    automated:
      selfHeal: true
      prune: true